/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

/**
 *
 * @author CrisDEV
 * clase modelo para mostrar zapatos de producto_variantes
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public interface Listener {
        void onAgregar(int idVariante, int idProducto, String nombre, String color, String talla);
    }

    private Listener listener;
    private Integer idBodega;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton btnBuscar;
    private javax.swing.table.DefaultTableModel model;
    private final java.util.Map<String, java.util.List<Object[]>> cache = new java.util.LinkedHashMap<String, java.util.List<Object[]>>() {
        protected boolean removeEldestEntry(java.util.Map.Entry<String, java.util.List<Object[]>> eldest) { return size() > 64; }
    };
    private final java.util.Map<Integer, javax.swing.ImageIcon> imageCache = new java.util.LinkedHashMap<Integer, javax.swing.ImageIcon>() {
        protected boolean removeEldestEntry(java.util.Map.Entry<Integer, javax.swing.ImageIcon> eldest) { return size() > 128; }
    };
    private javax.swing.SwingWorker<java.util.List<Object[]>, Void> worker;
    private final raven.clases.productos.ServiceProductVariant service = new raven.clases.productos.ServiceProductVariant();
    private static final int SEARCH_LIMIT = 60;
    private javax.swing.Timer debounce;

    public Productos() {
        initComponents();
        initSearchUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        model = new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"Nombre","Imagen","Color","Talla","Acciones"}){ public boolean isCellEditable(int r,int c){ return c==4; }};
        tabla.setModel(model);
        tabla.setRowHeight(48);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabla.getColumnModel().getColumn(4).setPreferredWidth(80);
        tabla.getColumnModel().getColumn(4).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer(){
            protected void setValue(Object value){ setText("Agregar"); setHorizontalAlignment(javax.swing.SwingConstants.CENTER); }
        });
        tabla.getColumnModel().getColumn(4).setCellEditor(new javax.swing.DefaultCellEditor(new javax.swing.JTextField()){ {
            final javax.swing.JButton btn = new javax.swing.JButton("Agregar");
            btn.addActionListener(e->{ int r = tabla.getSelectedRow(); if(r>=0 && listener!=null){ Object[] row = getRowData(r); listener.onAgregar((Integer)row[5], (Integer)row[6], String.valueOf(row[0]), String.valueOf(row[2]), String.valueOf(row[3])); }});
            editorComponent = btn;
            clickCountToStart = 1;
        }});
        tabla.putClientProperty("JTable.hiddenCols", new int[]{5,6});
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8,8,8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8,8,8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setListener(Listener l){ this.listener = l; }
    public void setIdBodega(Integer id){ this.idBodega = id; }
    private void initSearchUI(){
        txtSearch = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton("Buscar");
        btnBuscar.addActionListener(e->buscarAsync());
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter(){ public void keyReleased(java.awt.event.KeyEvent e){ if(debounce!=null && debounce.isRunning()) debounce.stop(); debounce = new javax.swing.Timer(200, ev->{ buscarAsync(); debounce.stop(); }); debounce.setRepeats(false); debounce.start(); }});
    }

    private void buscarAsync(){
        String term = txtSearch.getText()==null?"":txtSearch.getText().trim();
        if(worker!=null && !worker.isDone()){ worker.cancel(true); }
        worker = new javax.swing.SwingWorker<java.util.List<Object[]>, Void>(){
            @Override
            protected java.util.List<Object[]> doInBackground() {
                return cargarRows(term);
            }
            @Override
            protected void done() {
                if(isCancelled()) return;
                try{
                    java.util.List<Object[]> rows = get();
                    model.setRowCount(0);
                    for(Object[] r: rows){ model.addRow(new Object[]{ r[0], r[1], r[2], r[3], "Agregar", r[4], r[5] }); }
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
        };
        worker.execute();
    }

    private Object[] getRowData(int r){ return new Object[]{ model.getValueAt(r,0), model.getValueAt(r,1), model.getValueAt(r,2), model.getValueAt(r,3), model.getValueAt(r,4), model.getValueAt(r,5), model.getValueAt(r,6)}; }

    private java.util.List<Object[]> cargarRows(String term){
        String key = (idBodega!=null?"b:"+idBodega: "all")+"|"+term.toLowerCase();
        if(cache.containsKey(key)){ return cache.get(key); }
        java.util.List<Object[]> rows = consultar(term);
        cache.put(key, rows);
        return rows;
    }

    private java.util.List<Object[]> consultar(String term){
        java.util.List<Object[]> rows = new java.util.ArrayList<>();
        try{
            java.util.List<raven.clases.productos.ServiceProductVariant.VariantSearchResult> list = service.searchVariantsByTerm(term, idBodega, SEARCH_LIMIT);
            for(raven.clases.productos.ServiceProductVariant.VariantSearchResult v: list){
                javax.swing.ImageIcon icon = null;
                if(v.imageBytes!=null && v.imageBytes.length>0){
                    icon = imageCache.get(v.idVariante);
                    if(icon==null){
                        icon = crearIcono(v.imageBytes);
                        if(icon!=null){ imageCache.put(v.idVariante, icon); }
                    }
                }
                rows.add(new Object[]{ v.nombre, icon, v.colorNombre, v.tallaNombre, v.idVariante, v.idProducto });
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return rows;
    }

    private javax.swing.ImageIcon crearIcono(byte[] data){
        try{
            javax.swing.ImageIcon raw = new javax.swing.ImageIcon(data);
            int targetH = Math.max(36, tabla.getRowHeight());
            int w = raw.getIconWidth();
            int h = raw.getIconHeight();
            if(w <= 0 || h <= 0){ return raw; }
            double scale = (double) targetH / h;
            int targetW = Math.max(32, (int)(w * scale));
            java.awt.Image scaled = raw.getImage().getScaledInstance(targetW, targetH, java.awt.Image.SCALE_SMOOTH);
            return new javax.swing.ImageIcon(scaled);
        }catch(Exception e){
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
