package raven.application.form.productos.creates;

import raven.clases.productos.ServiceColor;
import raven.controlador.productos.ModelColor;

import raven.modal.Toast;

/**
 *
 * @author CrisDEV
 */
public class CreateColor extends javax.swing.JPanel {

    /**
     * Creates new form CreateColor
     */
    public CreateColor() {
        initComponents();
    }
    
    public ModelColor getData() {
        ModelColor color = new ModelColor();
        color.setNombre(txtNombre.getText().trim());
        color.setDescripcion(txtDescripcion.getText().trim());
        return color;
    }
    
    /**
     * Valida los datos del formulario antes de crear/actualizar
     * @param service Servicio para verificar duplicados
     * @return true si los datos son válidos, false en caso contrario
     */
    public boolean validateData(ServiceColor service) {
        String nombre = txtNombre.getText().trim();
        
        // Verificar que el nombre no esté vacío
        if (nombre.isEmpty()) {
            Toast.show(this, Toast.Type.WARNING, "El nombre del color es obligatorio");
            txtNombre.requestFocus();
            return false;
        }
        
        // Verificar que el nombre no sea demasiado largo (máximo 50 caracteres según la BD)
        if (nombre.length() > 50) {
            Toast.show(this, Toast.Type.WARNING, "El nombre del color no puede exceder 50 caracteres");
            txtNombre.requestFocus();
            return false;
        }
        
        // Verificar que no exista un color con el mismo nombre
        try {
            if (service.existeColor(nombre)) {
                Toast.show(this, Toast.Type.WARNING, "Ya existe un color con el nombre '" + nombre + "'");
                txtNombre.requestFocus();
                return false;
            }
        } catch (Exception e) {
            Toast.show(this, Toast.Type.ERROR, "Error al verificar duplicados: " + e.getMessage());
            return false;
        }
        
        return true;
    }
    
    /**
     * Valida los datos del formulario para edición (permite el mismo nombre si es el mismo color)
     * @param service Servicio para verificar duplicados
     * @param originalData Datos originales del color que se está editando
     * @return true si los datos son válidos, false en caso contrario
     */
    public boolean validateDataForEdit(ServiceColor service, ModelColor originalData) {
        String nombre = txtNombre.getText().trim();
        
        // Verificar que el nombre no esté vacío
        if (nombre.isEmpty()) {
            Toast.show(this, Toast.Type.WARNING, "El nombre del color es obligatorio");
            txtNombre.requestFocus();
            return false;
        }
        
        // Verificar que el nombre no sea demasiado largo
        if (nombre.length() > 50) {
            Toast.show(this, Toast.Type.WARNING, "El nombre del color no puede exceder 50 caracteres");
            txtNombre.requestFocus();
            return false;
        }
        
        // Si el nombre no cambió, no verificar duplicados
        if (originalData != null && nombre.equals(originalData.getNombre())) {
            return true;
        }
        
        // Verificar que no exista un color con el mismo nombre
        try {
            if (service.existeColor(nombre)) {
                Toast.show(this, Toast.Type.WARNING, "Ya existe un color con el nombre '" + nombre + "'");
                txtNombre.requestFocus();
                return false;
            }
        } catch (Exception e) {
            Toast.show(this, Toast.Type.ERROR, "Error al verificar duplicados: " + e.getMessage());
            return false;
        }
        
        return true;
    }
    
    public void loadData(ServiceColor service, ModelColor data) {
        // Si hay datos, cargar en los campos
        if (data != null) {
            txtNombre.setText(data.getNombre());
            txtDescripcion.setText(data.getDescripcion());
        }
    }
    
    public void init() {
        txtNombre.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Descripcion");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(txtDescripcion))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
