package raven.application.form.productos.creates;


import raven.clases.productos.ServiceCategory;
import raven.controlador.productos.ModelCategory;
import raven.modal.Toast;

/**
 *
 * @author RAVEN
 */
public class CreateCategory extends javax.swing.JPanel {

    public CreateCategory() {
        // Inicializa los componentes de la interfaz gráfica (generados automáticamente por NetBeans u otro IDE)
        initComponents();

    }

    public ModelCategory getData() {
        ModelCategory brand = new ModelCategory();
        brand.setName(txtNombre.getText().trim());
        brand.setDescription(txtDescripcion.getText().trim());
        return brand;

    }

    public boolean validateData(ServiceCategory service) {
        String nombre = txtNombre.getText().trim();
        if (nombre.isEmpty()) {
            Toast.show(this, Toast.Type.WARNING, "El nombre de la categoría es obligatorio");
            txtNombre.requestFocus();
            return false;
        }
        if (service.existeCategoria(nombre)) {
            Toast.show(this, Toast.Type.WARNING, "Ya existe una categoría con este nombre");
            txtNombre.requestFocus();
            return false;
        }
        return true;
    }

    public boolean validateDataForEdit(ServiceCategory service, ModelCategory currentData) {
        String nombre = txtNombre.getText().trim();
        if (nombre.isEmpty()) {
            Toast.show(this, Toast.Type.WARNING, "El nombre de la categoría es obligatorio");
            txtNombre.requestFocus();
            return false;
        }
        if (!currentData.getName().equalsIgnoreCase(nombre) && service.existeCategoria(nombre)) {
            Toast.show(this, Toast.Type.WARNING, "Ya existe una categoría con este nombre");
            txtNombre.requestFocus();
            return false;
        }
        return true;
    }

    public void loadData(ServiceCategory service, ModelCategory data) {

        // Si hay datos, cargar en los campos
        if (data != null) {

            txtNombre.setText(data.getName());
            txtDescripcion.setText(data.getDescription());

        }
    }







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker = new raven.datetime.component.date.DatePicker();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Descripcion");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(txtDescripcion))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed
    public void init() {
        txtNombre.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.datetime.component.date.DatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
