/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other.buscador;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

import raven.application.form.other.buscador.dto.VarianteDTO;

/**
 *
 * @author CrisDEV
 */
public class VarianteItemPanel extends javax.swing.JPanel {

    private final VarianteDTO variante;
    private Runnable seleccionListener;
    
    /**
     * Creates new form VarianteItemPanel
     */
    public VarianteItemPanel(VarianteDTO variante) {
         this.variante = variante;
        initComponents2();
        configurarEstilos();
    }
    
    /**
     * Crea una etiqueta de información con ancho fijo
     */
    private JLabel crearEtiquetaInfo(String texto, int ancho) {
        boolean dark = com.formdev.flatlaf.FlatLaf.isLafDark();
        JLabel label = new JLabel(texto);
        label.setPreferredSize(new Dimension(ancho, 20));
        label.setMinimumSize(new Dimension(ancho, 20));
        label.setMaximumSize(new Dimension(ancho, 20));
        label.setForeground(dark ? Color.WHITE : new Color(50, 50, 50));
        return label;
    }
    
    /**
     * Configura estilos FlatLaf
     */
    private void configurarEstilos() {
        putClientProperty(FlatClientProperties.STYLE, "arc: 8");
    }
    
    /**
     * Establece el listener para cuando se selecciona la variante
     */
    public void setSeleccionListener(Runnable listener) {
        this.seleccionListener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    /**
     * Inicializa componentes
     */
    private void initComponents2() {
        setLayout(new BorderLayout(10, 0));
        Color base = UIManager.getColor("Panel.background");
        setBackground(base);
        setBorder(new CompoundBorder(
            new LineBorder(UIManager.getColor("Component.borderColor"), 1, true),
            new EmptyBorder(8, 12, 8, 12)
        ));
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
        
        // Panel de información
        JPanel panelInfo = new JPanel();
        panelInfo.setLayout(new BoxLayout(panelInfo, BoxLayout.X_AXIS));
        panelInfo.setOpaque(false);
        
        // Talla
        JLabel lblTalla = crearEtiquetaInfo("Talla: " + variante.getTalla(), 100);
        panelInfo.add(lblTalla);
        panelInfo.add(Box.createHorizontalStrut(10));
        
        // Color
        JLabel lblColor = crearEtiquetaInfo("Color: " + variante.getColor(), 150);
        panelInfo.add(lblColor);
        panelInfo.add(Box.createHorizontalStrut(10));
        
        int stockDisponible = variante.getStockDisponible() != null ? 
                              variante.getStockDisponible() : 0;
        JLabel lblStock = crearEtiquetaInfo("Stock: " + stockDisponible, 80);
        
        // Colorear según disponibilidad
        if (stockDisponible <= 0) {
            lblStock.setForeground(Color.RED);
        } else if (stockDisponible < 5) {
            lblStock.setForeground(new Color(255, 140, 0)); // Naranja
        } else {
            lblStock.setForeground(new Color(0, 150, 0)); // Verde
        }
        
        panelInfo.add(lblStock);
        panelInfo.add(Box.createHorizontalStrut(10));
        
        int idVar = variante.getIdVariante() != null ? variante.getIdVariante() : 0;
        JLabel lblIdVar = crearEtiquetaInfo("ID Var: " + idVar, 90);
        panelInfo.add(lblIdVar);
        panelInfo.add(Box.createHorizontalStrut(10));

        String tipo;
        Integer stockCaja = variante.getStockCaja();
        Integer stockPares = variante.getStockPares();
        if (stockCaja != null && stockCaja > 0) {
            tipo = "Caja";
        } else if (stockPares != null && stockPares > 0) {
            tipo = "Par";
        } else {
            tipo = "Sin stock";
        }
        JLabel lblTipo = crearEtiquetaInfo("Tipo: " + tipo, 90);
        panelInfo.add(lblTipo);
        panelInfo.add(Box.createHorizontalStrut(10));

        // Precio
        if (variante.getPrecioVenta() != null) {
            JLabel lblPrecio = crearEtiquetaInfo(
                String.format("$%.2f", variante.getPrecioVenta()), 
                100
            );
            lblPrecio.setFont(lblPrecio.getFont().deriveFont(Font.BOLD));
            lblPrecio.setForeground(com.formdev.flatlaf.FlatLaf.isLafDark() ? Color.WHITE : new Color(40, 40, 40));
            panelInfo.add(lblPrecio);
        }
        
        add(panelInfo, BorderLayout.CENTER);
        
        // Botón de selección
        JButton btnSeleccionar = new JButton("Seleccionar");
        btnSeleccionar.setEnabled(stockDisponible > 0);
        btnSeleccionar.putClientProperty(FlatClientProperties.STYLE,
            "arc:18;background:#2D89EF;foreground:#ffffff;borderWidth:0;focusWidth:1");
        btnSeleccionar.addActionListener(e -> {
            if (seleccionListener != null) {
                seleccionListener.run();
            }
        });
        
        add(btnSeleccionar, BorderLayout.EAST);
        
        // Efecto hover
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (stockDisponible > 0) {
                    setBackground(adjustColor(UIManager.getColor("Panel.background"), 0.06f));
                    setBorder(new CompoundBorder(
                        new LineBorder(UIManager.getColor("Component.borderColor"), 1, true),
                        new EmptyBorder(8, 12, 8, 12)
                    ));
                }
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                setBackground(UIManager.getColor("Panel.background"));
                setBorder(new CompoundBorder(
                    new LineBorder(UIManager.getColor("Component.borderColor"), 1, true),
                    new EmptyBorder(8, 12, 8, 12)
                ));
            }
        });
    }

    private Color adjustColor(Color base, float ratio) {
        boolean dark = com.formdev.flatlaf.FlatLaf.isLafDark();
        Color mix = dark ? Color.WHITE : Color.BLACK;
        int r = (int) (base.getRed() * (1 - ratio) + mix.getRed() * ratio);
        int g = (int) (base.getGreen() * (1 - ratio) + mix.getGreen() * ratio);
        int b = (int) (base.getBlue() * (1 - ratio) + mix.getBlue() * ratio);
        return new Color(r, g, b, base.getAlpha());
    }
}
