/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raven.componentes.impresion;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author RAVEN
 */
public class PanelSearchC extends javax.swing.JPanel {

    private EventClickC event;

    public void addEventClickC(EventClickC event) {
        this.event = event;
    }

    public PanelSearchC() {
        initComponents();
        setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
        FlatRobotoFont.install();
        // Establece fuente predeterminada para todos los componentes
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        init();
    }
      private void init() {
    
    
    
    }

    // Lista de datos actual
    private List<DataSearchClient> currentData;
    
    /**
     * Obtiene el primer elemento de la lista de datos actual
     * @return El primer DataSearchClient de la lista o null si no hay elementos
     */
    public DataSearchClient getFirstItem() {
        if (currentData != null && !currentData.isEmpty()) {
            return currentData.get(0);
        }
        return null;
    }
    
    // Método para clientes
    public void setDataCliente(List<DataSearchClient> data, JPopupMenu menu) {
        this.removeAll();
        this.currentData = data; // Guardar referencia a los datos actuales
        for (DataSearchClient cl : data) {
            Search_ItemC item = new Search_ItemC(cl);
            item.addEvent(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if (event != null) {
                        event.itemClickC(cl);
                        menu.setVisible(false);
                    }
                }
            }, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if (event != null) {
                        event.itemRemoveC(item, cl);
                    }
                }
            });
            this.add(item, "wrap");
        }
        repaint();
        revalidate();
    }


    public int getItemSize() {
        return getComponentCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void addEventClick(EventClickC eventClickC) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
