/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raven.componentes.impresion;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author RAVEN
 */
public class PanelSearch extends javax.swing.JPanel {

    private EventClick event;

    public void addEventClick(EventClick event) {
        this.event = event;
    }

    public PanelSearch() {
        initComponents();
        setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
        FlatRobotoFont.install();
        // Establece fuente predeterminada para todos los componentes
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));

    }

    // Lista de datos actual
    private List<DataSearch> currentData;

    /**
     * Obtiene el primer elemento de la lista de datos actual
     * 
     * @return El primer DataSearch de la lista o null si no hay elementos
     */
    public DataSearch getFirstItem() {
        if (currentData != null && !currentData.isEmpty()) {
            return currentData.get(0);
        }
        return null;
    }

    // Método para productos
    public void setData(List<DataSearch> data, JPopupMenu menu) {
        this.removeAll();
        this.currentData = data; // Guardar referencia a los datos actuales
        for (DataSearch d : data) {
            Search_Item item = new Search_Item(d);
            item.addEvent(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if (event != null) {
                        event.itemClick(d);
                        menu.setVisible(false);
                    }
                }
            }, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if (event != null) {
                        event.itemRemove(item, d);
                    }
                }
            });
            this.add(item, "wrap");
        }
        repaint();
        revalidate();
    }

    public int getItemSize() {
        return getComponentCount();
    }

    /**
     * Simula un clic en el primer elemento de la lista (para Enter key)
     */
    public void selectFirstItem() {
        if (event != null && currentData != null && !currentData.isEmpty()) {
            event.itemClick(currentData.get(0));
        }
    }

    /**
     * Solicita el foco en el primer elemento de la lista (para navegación con
     * flechas)
     */
    public void requestFocusOnFirstItem() {
        if (getComponentCount() > 0) {
            java.awt.Component first = getComponent(0);
            if (first != null) {
                first.requestFocusInWindow();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 438, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
