/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raven.application.form.productos;

import raven.componentes.impresion.PanelSearch;
import raven.componentes.impresion.DataSearch;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import raven.clases.productos.ImpresorTermica;
import raven.componentes.CheckBoxTableHeaderRenderer;
import raven.componentes.impresion.EventClick;
import raven.controlador.principal.conexion;

/**
 *
 * @author RAVEN
 */
public class listaImprimir extends javax.swing.JFrame {

    private JPopupMenu menu;
    private PanelSearch search;

    public listaImprimir() {
        initComponents();
        tablaProd.getColumnModel().getColumn(6).setMinWidth(0);
        tablaProd.getColumnModel().getColumn(6).setMaxWidth(0);
        tablaProd.getColumnModel().getColumn(6).setWidth(0);
        tablaProd.getColumnModel().getColumn(0).setHeaderRenderer(new CheckBoxTableHeaderRenderer(tablaProd, 0));
        menu = new JPopupMenu();
        search = new PanelSearch();
        menu.setBorder(BorderFactory.createLineBorder(new Color(164, 164, 164)));
        menu.add(search);
        menu.setFocusable(false);
        search.addEventClick(new EventClick() {
            public void itemClick(DataSearch data) {
                menu.setVisible(false);
                txtSearch.setText(data.getEAN());
                System.out.print(data.toString() + "desde event");
                // Añadir fila a la JTable
                DefaultTableModel model = (DefaultTableModel) tablaProd.getModel();
                model.addRow(new Object[]{
                    false,
                    data.getEAN(),
                    data.getNombre(),
                    data.getColor(),
                    data.getTalla(),
                    1, // Valor por defecto para "CANTIDAD"
                    data.getId_prod(),});
                txtSearch.setText("");
            }

            public void itemRemove(Component com, DataSearch data) {
                search.remove(com);
                menu.setPopupSize(menu.getWidth(), (search.getItemSize() * 35) + 2);
                if (search.getItemSize() == 0) {
                    menu.setVisible(false);
                }
                System.out.println("Remove Item : " + data.getEAN());
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECCION", "EAN", "NOMBRE", "COLOR", "TALLA", "CANTIDAD", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProd);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSearch.setText("jTextField1");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 285, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private void updateSearchResults() {
        String text = txtSearch.getText().trim().toLowerCase();
        search.setData(search(text), menu);
        if (search.getItemSize() > 0) {
            menu.show(txtSearch, 0, txtSearch.getHeight());
            menu.setPopupSize(menu.getWidth(), (search.getItemSize() * 35) + 2);
        } else {
            menu.setVisible(false);
        }
    }

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        updateSearchResults();
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        updateSearchResults();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Recorremos la tabla y recopilamos los productos seleccionados
        for (int i = 0; i < tablaProd.getRowCount(); i++) {
            Boolean seleccionado = (Boolean) tablaProd.getValueAt(i, 0);
            if (seleccionado != null && seleccionado) {
                try {
                    int cantidad = Integer.parseInt(tablaProd.getValueAt(i, 5).toString());

                    // Creamos una nueva tabla temporal con solo esa fila
                    JTable tablaTemporal = new JTable(1, tablaProd.getColumnCount());
                    for (int j = 0; j < tablaProd.getColumnCount(); j++) {
                        tablaTemporal.setValueAt(tablaProd.getValueAt(i, j), 0, j);
                    }

                    // Instanciamos el impresor solo para esa fila
                    ImpresorTermica impresor = new ImpresorTermica(tablaTemporal, cantidad);
                    impresor.imprimir();

                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al imprimir fila " + i + ": " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private List<DataSearch> search(String search) {
        int limitData = 7;
        List<DataSearch> list = new ArrayList<>();
        String sql = "SELECT COALESCE(pv.ean, p.codigo_modelo) AS codigo_barras, p.id_producto, p.nombre, " +
                    "COALESCE(c.nombre, '') AS color, COALESCE(t.numero, '') AS talla " +
                    "FROM productos p " +
                    "LEFT JOIN producto_variantes pv ON p.id_producto = pv.id_producto " +
                    "LEFT JOIN colores c ON pv.id_color = c.id_color " +
                    "LEFT JOIN tallas t ON pv.id_talla = t.id_talla " +
                    "WHERE p.id_producto LIKE ? OR p.nombre LIKE ? OR c.nombre LIKE ? OR t.numero LIKE ? " +
                    "LIMIT ?";

        String url = "jdbc:mysql://" + conexion.host + ":" + conexion.port + "/" + conexion.database;
        try (Connection conn = DriverManager.getConnection(url, conexion.username, conexion.password); PreparedStatement stmt = conn.prepareStatement(sql)) {

            String searchParam = "%" + search + "%";
            stmt.setString(1, searchParam);
            stmt.setString(2, searchParam);
            stmt.setString(3, searchParam);
            stmt.setString(4, searchParam);
            stmt.setInt(5, limitData);

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String idpString = rs.getString("id_producto");
                String nombre = rs.getString("nombre");
                String color = rs.getString("color");
                String talla = rs.getString("talla");
                String codigoBarras = rs.getString("codigo_barras");

                boolean startsWithSearch = idpString.toLowerCase().startsWith(search.toLowerCase());
                DataSearch data = new DataSearch(idpString, codigoBarras, nombre, color, talla, startsWithSearch);

                if (startsWithSearch) {
                    list.add(0, data); // Prioriza los que empiezan con el texto
                } else {
                    list.add(data);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaImprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
