/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.principal;

/**
 *
 * @author Luis Ocampo
 */
public class panel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEstadoCaj = new javax.swing.JPanel();
        txtMovimientoCaja = new javax.swing.JLabel();
        btnGastos = new raven.componentes.GradientButton();
        btnCerrarCaja = new raven.componentes.GradientButton();
        btnBloquear = new raven.componentes.GradientButton();

        txtMovimientoCaja.setText("Mov: ");

        btnGastos.setText("Gastos");
        btnGastos.setColorFin(new java.awt.Color(217, 97, 25));
        btnGastos.setColorInicio(new java.awt.Color(245, 158, 11));
        btnGastos.setRippleColor(new java.awt.Color(255, 189, 13));
        btnGastos.setShadowColor(new java.awt.Color(255, 189, 13));
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });

        btnCerrarCaja.setText("Cerrar Caja");
        btnCerrarCaja.setColorFin(new java.awt.Color(124, 58, 237));
        btnCerrarCaja.setColorInicio(new java.awt.Color(0, 20, 122));
        btnCerrarCaja.setRippleColor(new java.awt.Color(255, 189, 13));
        btnCerrarCaja.setShadowColor(new java.awt.Color(255, 189, 13));
        btnCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCajaActionPerformed(evt);
            }
        });

        btnBloquear.setText("Bloquear");
        btnBloquear.setColorFin(new java.awt.Color(217, 0, 62));
        btnBloquear.setColorInicio(new java.awt.Color(220, 38, 38));
        btnBloquear.setRippleColor(new java.awt.Color(255, 189, 13));
        btnBloquear.setShadowColor(new java.awt.Color(255, 189, 13));
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstadoCajLayout = new javax.swing.GroupLayout(panelEstadoCaj);
        panelEstadoCaj.setLayout(panelEstadoCajLayout);
        panelEstadoCajLayout.setHorizontalGroup(
            panelEstadoCajLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoCajLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMovimientoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEstadoCajLayout.setVerticalGroup(
            panelEstadoCajLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoCajLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadoCajLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadoCajLayout.createSequentialGroup()
                        .addGroup(panelEstadoCajLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBloquear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtMovimientoCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelEstadoCaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(panelEstadoCaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(122, 122, 122)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGastosActionPerformed

    private void btnCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCajaActionPerformed
     
    }//GEN-LAST:event_btnCerrarCajaActionPerformed

    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
     
    }//GEN-LAST:event_btnBloquearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.componentes.GradientButton btnBloquear;
    private raven.componentes.GradientButton btnCerrarCaja;
    private raven.componentes.GradientButton btnGastos;
    private javax.swing.JPanel panelEstadoCaj;
    private javax.swing.JLabel txtMovimientoCaja;
    // End of variables declaration//GEN-END:variables
}
